CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT UNIQUE, pw TEXT, role TEXT);
CREATE TABLE teachers (id SERIAL PRIMARY KEY, name TEXT, user_id INTEGER REFERENCES users);
CREATE TABLE courses (id SERIAL PRIMARY KEY, course TEXT, teacher_id INTEGER REFERENCES teachers);
CREATE TABLE goals (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users, course_id INTEGER REFERENCES courses, goal INTEGER, studied INTEGER, completed BOOLEAN DEFAULT FALSE, deleted BOOLEAN DEFAULT FALSE);

